dashboard/urls.py
from django.urls import path
import dashboard.views

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard.views.MainDashboardView.as_view(), name='main'),
]

sec/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import dashboard.views
import debug_toolbar

urlpatterns = [
    path('', dashboard.views.MainDashboardView.as_view(), name='home'),  # can change to anything
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # for allauth
    path('', include('dashboard.urls')),
    path('sec/api/v1/', include('restapi.urls')),
    path('task/', include('taskmanagement.urls')),
    path('store/', include('store.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

taskmanagement/urls.py
from django.urls import path
import taskmanagement.views

app_name = 'tasks'

urlpatterns = [
    path('add', taskmanagement.views.AddTaskView.as_view(), name='add'),
    path('list', taskmanagement.views.ListTaskView.as_view(), name='list'),
]

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.template import loader
from django.http import HttpResponse

class MainDashboardView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        company_content = {
            
        }
        template_loader = loader.get_template('dashboard_company.html')
        response = HttpResponse(template_loader.render(company_content, request))

        return response

dashboard/templates/dashboard/dashboard_company.html
{% extends "master.html" %}

{% block main_content %}
    <p>Successfully log in</p>
{% endblock %}

dashboard/templates/dashboard/master_footer.html
{% load static %}

<footer class="app-footer">
    <span>
        © 2019 LearningApp
    </span>
    <span class="ml-auto">
        <a href="">Self Learning</a>
    </span>
</footer>

dashboard/templates/dashboard/master_header.html
{% load static %}
{% load i18n %}

{% block main_css %}
	<link href="{% static 'css/master_header.css' %}" rel="stylesheet">
{% endblock %}

<header class="app-header navbar">
    <a class="navbar-brand" href="">
        <img class="navbar-brand-full" src="{% static 'img/icon.png' %}" height="35" alt="app Logo">
        <img class="navbar-brand-minimized" src="{% static 'img/icon.png' %}" height="25" alt="app Logo">
    </a>
    <!-- hidden only om small laptops -->
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show" id="navbar_toggler">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- boostrap navigation bar -->
    <ul class="nav navbar-nav d-md-down-none">
        <!-- padding left and right -->
        <li class="nav-item px-3">
            <a class="nav-link" href="">{% trans 'Dashboard' %}</a>
        </li>
    </ul>
    <!-- bootstrap navigation bar with dropdown -->
    <ul class="nav navbar-nav ml-auto">
        <div>
          <span>{% trans 'Welcome' %}</span>
        </div>
        <li class="nav-item dropdown">
            <!-- bootstrap dropdown -->
            <a class="nav-link nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                aria-expanded="false">
                <span class="material-icons">account_circle</span>
            </a>
            <!-- boostrap dropdown selection -->
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>{% trans 'Settings' %}</strong>
                </div>
                <div class="divider"></div>
                <a class="dropdown-item" href="">
                    <i class="nav-icon material-icons align-middle">check</i>
                    {% trans 'Profile Settings' %}
                </a>
                <a class="dropdown-item" href="">
                    <!-- vertical alignment -->
                    <i class="nav-icon material-icons align-middle">settings</i>
                    {% trans 'Company Settings' %}
                </a>
                <a class="dropdown-item" href="" onclick="event.preventDefault(); document.getElementById('logout_form').submit()">
                    <i class="nav-icon material-icons align-middle">power_settings_new</i>
                    {% trans 'Logout' %}
                </a>
            </div>
        </li>
    </ul>
    <!-- logout URL provided by django-allauth -->
    <form class="form-group" id="logout_form" method="POST" action="{% url 'account_logout' %}" style="display:none" novalidate="">
        {% csrf_token %}
        {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
    </form>
</header>

dashboard/templates/dashboard/master_left_sidebar.html
<div class="sidebar">
    <nav class="sidebar-nav">
      <ul class="nav">
        <li class="nav-title">Nav Title</li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="nav-icon material-icons align-middle">home</i> Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:list' %}">
            <i class="nav-icon material-icons align-middle">check_circle</i> Task
          </a>
        </li>
        <li class="nav-item nav-dropdown">
          <a class="nav-link nav-dropdown-toggle" href="#">
            <i class="nav-icon material-icons align-middle">people</i> User
          </a>
          <ul class="nav-dropdown-items">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon material-icons align-middle">assignment_ind</i> Active user
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon material-icons align-middle">list</i> Inactive user
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>